name: 'duckdb'
version: '1.0.0'
profile: 'duckdb'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  duckdb:
    bronze:
      +schema: bronze
      +materialized: table
      +tags: ['bronze']

    silver:
      +schema: silver
      +materialized: table
      +tags: ['silver']

    gold:
      +schema: gold
      +materialized: table
      +tags: ['gold']

    cx:
      +schema: cx
      +materialized: view
      +tags: ['conformed_layer']